source 'https://rubygems.org'

gem 'httparty', '0.13.5'
gem 'devise', '3.4.1'

gem 'rails', '4.2.1'
gem 'pg', '0.18.2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails', '4.0.3'
gem 'turbolinks', '2.5.3'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'pry-rails', '0.3.4'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

